services:
  # Backend Service
  - type: web
    name: socialscope-backend
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: BASE_API_URL
        value: https://api.langflow.astra.datastax.com
      - key: LANGFLOW_ID
        sync: false
      - key: FLOW_ID
        sync: false
      - key: APPLICATION_TOKEN
        sync: false

  # Frontend Service
  - type: web
    name: socialscope-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          name: socialscope-backend
          type: web
          property: url 