services:
  - type: web
    name: your-api-name
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PORT
        value: 5000
      - key: FLASK_ENV
        value: production 